### ISSUE TITLE
BinsonWriter int64 support for php32

### ISSUE THREAD

**Issue by ppmag** [assaabloy-ppi/binson-php#10]
Idea is simple:  allow `float` argument in `putInteger()`.
If integer is whole number, pack it, and throw exception otherwise.

**Comment by franslundberg** [comment]
Is 32-bit support needed? PHP runs on servers normally. I cannot think of any use case for 32-bit PHP, really. Does anyone use 32-bit systems anymore? Server-side? I don't know.

**Comment by ppmag** [comment]
I think only for compatibility, maybe in VMs.... but, really, 95% of customers should use php64.
If we can ignore (better to say, ask to update hosting stuff) that 5% - no problem, let's skip this.

**Comment by ppmag** [comment]
ok, let's ignore php32.
