### ISSUE TITLE
Numeric field names NOT supported

### ISSUE THREAD

**Issue by ppmag** [assaabloy-ppi/binson-php#12]
Fuzzing rulez, finally.

Due to PHP's loose typing  we can't support in PHP numeric OBJECT field names.

We have problem with e.g.:
```
{"12" => true}
```
PHP silently convert "12" to int(12) and will decide above is NOT associative key-val pair, but just value `true` with index 12.
But... why expect something better from language which evaluates expression `"12" == 12` to `true`.

BTW, same issue may happen in `binson-js` since JS also loosely typed.

For now I can see two way-outs:
1. declare `binson-php` doesn't support numeric fieldnames.
2.  add suffix `.` to all numeric fieldnames in PHP associative arrays to disable automatic casting. Suffix should be stripped from raw binson bytes instantly. It will exist only in PHP representation.  Ascii code of dot is less than of '0', so lexicographic order will remain preserved.

**Comment by ppmag** [comment]
fixed in a9c115995344eff257326833eac6596680973452, 
* need more fuzzing
* need to add README section regarding requirements for php-array to be serializable to binson.

**Comment by DmSProject** [comment]
Just tested this:

```
$test = [
                '12' => 'cool',
                'cool'=> 12
              ];
error_log('test: '.print_r($test,true));
```

That returns an associative array with a mix of numeric and string keys as far as I can see.
there is a big difference between enclosing a string with "" or ''
If you use "" you allow variable parsing inside the string without concatenating it, like this:
$nr_years = 18;
echo "Mike is $nr_years old";
compared to:
echo  'Mike is '.$nr_years.' old';

I'm pretty sure that enclosing a numeric value as a string-key in a n array with "12" will allow PHP to interpret it as it sees fit, in this case as an int. Try it with '12' and I'm 99% sure it will be a numeric string, as intended.

I've basically stopped using "" around strings for this exact reason

**Comment by ppmag** [comment]
Сounterexample:
http://sandbox.onlinephpfunctions.com/code/abe1f4b6a19358a66242a98f6762187ad4b081d7
(runnable code)

Here we can see, no matter what index is (12, '12', "12"), finally there is an only item in the array with index int(12), so array is not associative.

Also official manual declares above is not bug, but PHP's array nature.
From http://php.net/manual/en/language.types.array.php

> Additionally the following key casts will occur:
> 
> * Strings containing valid decimal integers, unless the number is preceded by a + sign, will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
> *  Floats are also cast to integers, which means that the fractional part will be truncated. E.g. the key 8.7 will actually be stored under 8.
> * Bools are cast to integers, too, i.e. the key true will actually be stored under 1 and the key false under 0.
> * Null will be cast to the empty string, i.e. the key null will actually be stored under "".
> * Arrays and objects can not be used as keys. Doing so will result in a warning: Illegal offset type.
> If multiple elements in the array declaration use the same key, only the last one will be used as all others are overwritten.

Yep, it's why I never choose PHP for own projects... too much intelligence, error-prone design...

**Comment by ppmag** [comment]
There are huge discussions on this issue in json community... since above specific makes many difficulties and means impossibility to do automated tests like  json_decode(json_encode()).

PS:  we can in binson, if don't use int strings or if add dot suffix to int-like keys,

**Comment by DmSProject** [comment]
Ok, fair enough.

**Comment by DmSProject** [comment]
Had to test this a bit more:

```
$test = [
                '12' => 'cool',
                'cool'=> 12
              ];
              error_log('test arr: '.print_r($test,true));
              $json_test = json_encode($test);
              error_log('test json: '.$json_test);
              $obj = json_decode($json_test);
              error_log('test obj from json: '.print_r($obj,true));

              foreach ($obj as $key => $value) {
                error_log('key: '.gettype($key).' val: '.gettype($value));
             }
```

gave this result:

```
[02-Oct-2018 14:03:14 UTC] test arr: Array
(
    [12] => cool
    [cool] => 12
)

[02-Oct-2018 14:03:14 UTC] test json: {"12":"cool","cool":12}
[02-Oct-2018 14:03:14 UTC] test obj from json: stdClass Object
(
    [12] => cool
    [cool] => 12
)

[02-Oct-2018 14:03:14 UTC] key: string val: string
[02-Oct-2018 14:03:14 UTC] key: string val: integer
```

I guess I'm missing something here :) 

But never mind this, if a lot of ppl have issues with it, I'm sure there are issues :)

**Comment by ppmag** [comment]
Very interesting!
And even more:  
http://sandbox.onlinephpfunctions.com/code/3d809cc70200cf8973347a9b1293f47824f2dd73

Resume:
1) json_decode() returns NOT array but stdClass object by default.
2) This makes impossible to compare source and result with `===` (even after casting!).
3) Casted stdClass to array still keeps stdClass's behavior - keeps string numeric keys! (looks for me totally undocumented - only StackOverflow accepts this)
4) If call  json_decode()  with second arg set to TRUE, it will return array with bunch of problems but comparable.

More interesting results with json_encode():
http://sandbox.onlinephpfunctions.com/code/444d302a7a29b387bf196f27cab048398566d337

That's making me crazy :)

Tons of aspects, but looks like the best way is to mimic json behaviour:

1) Accept arrays & stdClass as input for encoding
2) Return strClass by default, otherwise array if optional argument set to true.
3) One can then cast stdClass to array and have no limitations with keys.

**Comment by ppmag** [comment]
... even more crazy: =)
After reading first section "Converting numeric keys in object/array casts" here:
https://ndench.github.io/brisphp/brisphp-news-2018-03-01

I tried first link (from prev. comment) in versions PHP7.1 and PHP7.2  and get totally different comparison results and key types.
So big differences in last versions.... that's not funny....

**Comment by ppmag** [comment]
Now supported.
See unittests in `tests/3_Serialization/1_ObjectSerializationTest.php`
