### ISSUE TITLE
parser->verify() issues

### ISSUE THREAD

**Issue by DmSProject** [assaabloy-ppi/binson-php#16]
As you have heard over skype and from Kuba, there are ongoing issues with verifying binson.
I'll summarize what I know here so we can track it.

As of right now, 13.00 9th Oct, we can verify and parse binson messages in the following scenarios.
On siteground servers using PHP version 7.0.x and 7.1.x
In my local MAMP install under both 7.1.20 and 7.2.8

It does not work on siteground servers with PHP 7.2.10
It fails on $parser->verify()
If I bypass that and go directly to binson_decode() it also fails and returns nothing.

Backwards compatability is all good, but not if it doesn't work on the stable and used PHP versions recommended by wordpress (7.2+). Also see Frans email from today in regards to php target versions.

**Comment by ppmag** [comment]
Hi Dan,  sorry for delayed answer....

current status:
1) backward compatibility updates removed (now minimal is 7.2.x)
2) Kuba found two important issues - in the repo
3) README updated, phpunit also reverted to last version.

So please after pulling repo updates please also run "make update"

Please let me know if this issue may be claimed as fixed,

**Comment by DmSProject** [comment]
I can confirm that I can now run binson.php on the live servers, both under 7.1 and 7.2 :) 
I have not tested 7.0, but that's not to be supported.

**Comment by ppmag** [comment]
Great!  Thank you, Dan!
