### ISSUE TITLE
Looking for a way to represent BYTES binson type in PHP

### ISSUE THREAD

**Issue by ppmag** [assaabloy-ppi/binson-php#5]
There are no binary buffers in PHP, strings are the only type.
No, reversed....
PHP's type named 'string' is in real, binary buffer,
It is not  zero-terminated, may contain any bytes.

E.g. we want to serialize next php-array 
```php
[1,2,'\x01\x02\x03']
```
Serializer needs to choose binson type for last item (BYTES vs STRING).

The only way I can see is to prepend  "binary" php-string with signature, let's say \0x00,
to let serializer know next bytes should be encoded as BYTES,
instead of default STRING.

Formally, NUL (\0) is valid UTF-8 item, but I hope should not be used in practice....
In super-rare cases when UTF-8 string with starting \0 is required, I'd suggest don't use PHP-serializer,
but write it with low-level API (->putBytes())

So
```php
$writer->put( [1,2,'\x01\x02\x03'] );
$writer->put( [1,2,'\x00\x01\x02\x03'] );
```
will store same data in third binson item, but first one will be STRING, and second will be BYTES.

Better ideas?

**Comment by franslundberg** [comment]
I might not understand. Why not:

    $writer->putString(....)
    // and:
    $writer->putBytes(...)

**Comment by ppmag** [comment]
No problem at all with:
```php
$writer->putString(....)
// and:
$writer->putBytes(...)
```
The question is related to upper API level - serialization of arbitrary PHP nested structures (called in PHP arrays ).

**Comment by ppmag** [comment]
Nice to have a way converting to binson any php structures with one put() call:

```php
$result_array = mysql_fetch_array($result)
$result_array['index_1']['index_2'] = 'some important updates';
...
$writer->put($result_array);
```

BTW, put() serializer already implemented.

**Comment by ppmag** [comment]
It may looks for lib user as following:

```php
$array = [
    "regular_string",
    binson::TYPE_BYTES_PREFIX."\x01\x02\x03"  // will be encoded as BYTES binson item 
];

$writer->put($array);
...

**Comment by ppmag** [comment]
I realized, my proposal has major flaws,
so for now it will be implemented this way:

if config option 'serializer_bytes_fallback' is set to **true**, parser will check all string to be valid UTF8 during serialization, and will encode it in BYTES if not (instead of STRING).

if config option 'serializer_bytes_fallback' is set to **false**, all PHP string-like array members will be encoded as binson STRING without any checks.

**Comment by franslundberg** [comment]
Now, I understand. I think. 

We need a way to handle this. High-level API must have a way to BOTH add strings and bytes. Not sure how to solve it. If possible at all with the current approach.

**Comment by franslundberg** [comment]
To be able to use the high-level API, we need support for both Binson strings and Binson bytes. Those are very common for our use cases.

Not sure how to proceed. Do we have to give up the direct mapping between built-in PHP associative array and a Binson object? Do we need a special Binson PHP class to represent a Binson object in memory?

**Comment by ppmag** [comment]
Working on it.... I hope I'll  find something...

**Comment by ppmag** [comment]
Now looks trivial.....

What about notation like this:
```php
$arr1 = ['a'= > binson::BYTES('this string is body of binson BYTES item')];

// next two lines are identical (produce same binson output)
$arr2 = ['a'= > 'this string is body of binson STRING item')];
$arr3 = ['a'= > binson::STRING('this string is body of binson STRING item')];
```

....implementation should be also trivial.

**Comment by franslundberg** [comment]
We like it :-) Please, go ahead and implement it!

**Comment by ppmag** [comment]
fixed, updated example in README, unit tests added.
