### ISSUE TITLE
Binson byte representaation do not have alpabetical sorted fields

### ISSUE THREAD

**Issue by TheHawkis** [assaabloy-ppi/binson-php#9]
When I and Dan was working on Binson PHP I noted that the byte representation of binson did not have the fields sorted alphabetically. This is part of the standard.

**Comment by ppmag** [comment]
That's true,
in `put()` call it will be implemented very soon (reorder fields while serializing),
...however don't planned in low-level API (`$writer->putName('a')`) since it's low-level, and sorting is definitely task for upper abstraction layer.
